#!/bin/sh
# Load the rotary switch module and create /dev/rotary_switch.

module="rotary_switch"	
device="rotary_switch"	
mode="664"

set -e

modprobe $module || exit 1

major=$(awk "\$2==\"$device\" {print \$1}" /proc/devices)
if [ -z "$major" ]; then
	echo "$device not found in /proc/devices"
	exit 1
fi

rm -f /dev/${device}
mknod /dev/${device} c $major 0
chmod $mode /dev/${device}